[build]
builder = "dockerfile"

[deploy]
startCommand = "node src/index.js"
restartPolicyMaxRetries = 5

[env]
PORT = { value = "", required = true }
DATABASE_URL = { value = "", required = true }
JWT_SECRET = { value = "", required = true }
MINIO_ENDPOINT = { value = "", required = true }
MINIO_ACCESS_KEY = { value = "", required = true }
MINIO_SECRET_KEY = { value = "", required = true }
MINIO_BUCKET = { value = "", required = true }
MINIO_USE_SSL = { value = "", required = true }
NODE_ENV = { value = "", required = true }
